<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="ss-PC" name="com.api.test.VerifyAssets_Events_Bundle_APIs" tests="31" failures="6" timestamp="31 Jan 2019 08:57:25 GMT" time="22.572" errors="0">
  <testcase name="verifyAssetCreationWithoutContentType" time="0.782" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyAssetCreationWithoutContentType(VerifyAssets_Events_Bundle_APIs.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAssetCreationWithoutContentType -->
  <testcase name="verifyAssetCreationWithDuplicateValidData" time="0.672" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="Error..!! Getting Error while creation Asset with duplicate data. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error..!! Getting Error while creation Asset with duplicate data. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyAssetCreationWithDuplicateValidData(VerifyAssets_Events_Bundle_APIs.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAssetCreationWithDuplicateValidData -->
  <testcase name="verifyFindAssetWithValidParameter" time="1.171" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindAssetWithInValidParameter" time="0.633" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidEventsWithParameter" time="0.859" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidEvents" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyFindValidEvents -->
  <testcase name="verifyFindAssetWithValidParameter" time="0.641" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyAssetCreationWithInvalidSecretKey" time="0.860" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="Error..!! Getting Error while creation Asset with duplicate data. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error..!! Getting Error while creation Asset with duplicate data. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyAssetCreationWithInvalidSecretKey(VerifyAssets_Events_Bundle_APIs.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAssetCreationWithInvalidSecretKey -->
  <testcase name="verifyFindAssetWithValidParameter" time="0.844" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidEventsWithParameter" time="1.157" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyEventCreationWithInvalidSecretKey" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyEventCreationWithInvalidSecretKey -->
  <testcase name="verifyAssetCreationWithValidData" time="0.845" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindInvalidEvents" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyFindInvalidEvents -->
  <testcase name="verifyFindAssetWithValidParameter" time="0.814" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyEventCreationWithValidData" time="0.828" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="Event not created successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Event not created successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.amb.api.Events.createEvent(Events.java:38)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyEventCreationWithValidData(VerifyAssets_Events_Bundle_APIs.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyEventCreationWithValidData -->
  <testcase name="verifyFindAssetWithInValidParameter" time="0.844" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindAssetInvalidID" time="0.843" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindAssetWithInValidParameter" time="0.845" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidEventsWithParameter" time="0.625" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidEventsWithParameter" time="1.031" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyEventCreationWithoutSecretKey" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyEventCreationWithoutSecretKey -->
  <testcase name="verifyFindInvalidBundle" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyFindInvalidBundle -->
  <testcase name="verifyFindValidEventsWithParameter" time="0.798" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyEventCreationWithoutContentType" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyEventCreationWithoutContentType -->
  <testcase name="verifyFindValidAsset" time="0.814" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindAssetWithValidParameter" time="1.187" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyAssetCreationWithoutSecretKey" time="0.829" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyAssetCreationWithoutSecretKey(VerifyAssets_Events_Bundle_APIs.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAssetCreationWithoutSecretKey -->
  <testcase name="verifyAssetCreationWithInvalidFormatSecretKey" time="3.761" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <failure type="java.lang.AssertionError" message="Error..!! Getting Error while creation Asset with Invalid data. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error..!! Getting Error while creation Asset with Invalid data. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.api.test.VerifyAssets_Events_Bundle_APIs.verifyAssetCreationWithInvalidFormatSecretKey(VerifyAssets_Events_Bundle_APIs.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAssetCreationWithInvalidFormatSecretKey -->
  <testcase name="verifyEventCreationWithDuplicateValidData" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyEventCreationWithDuplicateValidData -->
  <testcase name="verifyFindAssetWithInValidParameter" time="0.889" classname="com.api.test.VerifyAssets_Events_Bundle_APIs"/>
  <testcase name="verifyFindValidBundle" time="0.000" classname="com.api.test.VerifyAssets_Events_Bundle_APIs">
    <skipped/>
  </testcase> <!-- verifyFindValidBundle -->
</testsuite> <!-- com.api.test.VerifyAssets_Events_Bundle_APIs -->
